name: introtoflutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # This is how we declare an assets folder.
  assets:

    #This doesnt have to be called assets but it is for now.
    - images/ # This is where we will put our images.

  # This is how we define fonts and link them from the fonts folder.
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf